// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbELmpW30ElHyqOFUxxxbS0hMy1tuUlfA',
    appId: '1:511559276850:web:a1a12495610817f3629f2b',
    messagingSenderId: '511559276850',
    projectId: 'sugar-437011',
    authDomain: 'sugar-437011.firebaseapp.com',
    storageBucket: 'sugar-437011.appspot.com',
    measurementId: 'G-NYMJZ78RG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkkyF-xgieSlwtu-ci289KzbpUpX_V2Rw',
    appId: '1:511559276850:android:f87ba6af1af61393629f2b',
    messagingSenderId: '511559276850',
    projectId: 'sugar-437011',
    storageBucket: 'sugar-437011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_lrT8ynr1b4e_EW-V3qTiAT0pFyJpeLs',
    appId: '1:511559276850:ios:3bf6e77a24942295629f2b',
    messagingSenderId: '511559276850',
    projectId: 'sugar-437011',
    storageBucket: 'sugar-437011.appspot.com',
    androidClientId: '511559276850-a64rvj07blo1fh3p5r956nm75jrcte29.apps.googleusercontent.com',
    iosBundleId: 'com.venxkakima.sugar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_lrT8ynr1b4e_EW-V3qTiAT0pFyJpeLs',
    appId: '1:511559276850:ios:3bf6e77a24942295629f2b',
    messagingSenderId: '511559276850',
    projectId: 'sugar-437011',
    storageBucket: 'sugar-437011.appspot.com',
    androidClientId: '511559276850-a64rvj07blo1fh3p5r956nm75jrcte29.apps.googleusercontent.com',
    iosBundleId: 'com.venxkakima.sugar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbELmpW30ElHyqOFUxxxbS0hMy1tuUlfA',
    appId: '1:511559276850:web:69892d591370da12629f2b',
    messagingSenderId: '511559276850',
    projectId: 'sugar-437011',
    authDomain: 'sugar-437011.firebaseapp.com',
    storageBucket: 'sugar-437011.appspot.com',
    measurementId: 'G-V50SBXY22N',
  );
}
